name: Test (bot trigger)

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  test:
    if: contains(fromJSON('["github-actions[bot]", "renovate[bot]"]'), github.actor)
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        run: pnpm -s test
